#FIRST SHIPMENT_ID(외래), FLAVOR(기본), TOTAL_ORDER
#JULY SHIPMENT_ID(기본), FLAVOR(외럐), TOTAL_ORDER

SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN JULY 
ON FH.FLAVOR = JULY.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(JULY.TOTAL_ORDER + FH.TOTAL_ORDER) DESC
LIMIT 3
